/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Reading = IDL.Record({
  'id' : IDL.Nat,
  'value' : IDL.Float64,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addReading' : IDL.Func([IDL.Float64], [Reading], []),
  'getAllReadings' : IDL.Func([], [IDL.Vec(Reading)], ['query']),
  'getLatestReading' : IDL.Func([], [Reading], ['query']),
  'sayHello' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Reading = IDL.Record({
    'id' : IDL.Nat,
    'value' : IDL.Float64,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addReading' : IDL.Func([IDL.Float64], [Reading], []),
    'getAllReadings' : IDL.Func([], [IDL.Vec(Reading)], ['query']),
    'getLatestReading' : IDL.Func([], [Reading], ['query']),
    'sayHello' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };